#!/bin/sh

set -e

case "$1" in
    remove)
        userdel -r jerrybuild
        invoke-rc.d jerrybuild stop
        update-rc.d -f jerrybuild remove
        ;;
    purge)
        rm -rf /var/lib/jerrybuild
        ;;
esac

exit 0
