#!/bin/sh

set -e

case "$1" in
    configure)
        adduser --system --disabled-password --home /var/lib/jerrybuild \
                --shell /bin/sh --no-create-home --quiet --force-badname \
                --group jerrybuild
        chown jerrybuild:jerrybuild /var/lib/jerrybuild -R
        update-rc.d jerrybuild defaults
        ;;
esac

exit 0
