#!/bin/sh

set -e

case "$1" in
    remove)
        update-rc.d -f jerrybuild remove
        userdel -r jerrybuild
        ;;
    purge)
        rm -rf /var/lib/jerrybuild
        rm -rf /etc/jerrybuild
        ;;
esac

exit 0
