.TH MAN 1 "2016-06-30" "%%VERSION%%" "Jerrybuild"

.SH NAME
jerrybuild - A lightweight build server

.SH SYNOPSIS
.B jerrybuild
.RB <configfile>

.SH DESCRIPTION

Jerrybuild is a lightweight project build and Continuous Integration server
written in Python. Basically, it's a web server that listens for webhook
notifications and then runs scripts. The output is viewable in a web interface.

.SH OPTIONS

Jerrybuild has no options. It is configured in the configfile.

.SH SEE ALSO

\fIREADME.md\fR, start here.

.SH COPYRIGHT

jerrybuild is copyright 2016 by Ferry Boender

Ferry Boneder
ferry.boender@gmail.com

