site_name: Jerrybuild
theme: readthedocs
nav:
  - About: index.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - Providers: providers.md
  - Cookbook: cookbook.md
extra_css:
  - css/extra.css
